version: '3.8'
name: ${NAMESPACE_PREFIX}

services:
  lightrag:
    build: .
    ports:
      - "127.0.0.1:9621:9621"
    volumes:
      - ./data/rag_storage:/app/data/rag_storage
      - ./data/inputs:/app/data/inputs
      - .env:/app/.env
    env_file:
      - .env
    environment:
      - TZ=UTC
    restart: unless-stopped
    networks:
      - lightrag_net
      - lightrag_pgdb_network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  lightrag_net:
    driver: bridge
  lightrag_pgdb_network:
    name: lightrag_pgdb_network
    external: true
